### ISSUE TITLE
After installing RPL Attack Framwork "collect-view tool" is not there

### ISSUE THREAD

**Issue by dmabm** [dhondta/rpl-attacks#24]
Hi,

After installing RPL Attack Framwork "collect-view tool" is not appear in the Cooja simulator  (See the following images for Before and after installing the Framework available tools in the Cooja simulator )

See before installing at the very bottom in the drop down menu for "collect-view tool" (No Visualizer Screenshot...)

![a](https://cloud.githubusercontent.com/assets/26753923/24481796/7875347e-14b2-11e7-9562-d7b16ccb3100.PNG)

See after the installing at the very bottom in the drop down menu for "collect-view tool" (But Visualizer Screenshot.. is added to the menu somewhere in the middle)

![b](https://cloud.githubusercontent.com/assets/26753923/24481798/7d727932-14b2-11e7-95ed-b1d4f93159c8.PNG)

Please let me know how to add "collect-view tool" after installing the RPL Attack Framwork

Thank you very much
Akalanka (dmabm)

**Comment by dhondta** [comment]
Hi,

**Reason**: RPL Attacks Framework's setup command adapts Cooja's `.cooja.user.properties` in the following way :
- If the file exists, the line starting with `DEFAULT_PROJECTDIRS=` is adapted so that it loads the custom plugin *Visualizer Screenshot* (which is in fact a class extension of the *Visualizer*).
- If the file does not exist, it is created based on the template provided in the RPL Attacks Framework Git project, which only handles the required plugins (and **NOT the *Collect View* plugin**).

**Solution**: Manually configure the plugin through the GUI according to Cooja's documentation of Contiki.

**Comment by dmabm** [comment]
Hi dhondta,

I was able to Manually configured Collect View plugin with the RPL attack framework and now everything works fine. Thank you very much for your help.

Actually I may need you help in the future with my research and I wanted to add some  more attacks to this framework, so could you please let me know much easier contacting way to keep in touch with you. 

I am also looking for a problem to work with my thesis on IoT security with Cooja/Contiki, if you have any idea please be kind enough to share with me.   

Thanks again
Akalanka (dmabm)
