### ISSUE TITLE
problem black hole

### ISSUE THREAD

**Issue by sonxay** [dhondta/rpl-attacks#28]
hi.....I am Sonxay

this is my problem ....it is not have series.log in the example

Did you get the image

![screen shot 2017-06-20 at 1 41 59 pm](https://user-images.githubusercontent.com/29446281/27320119-e728539a-55be-11e7-8126-35c6392d2ed2.png)

**Comment by SwitchIsMine** [comment]
Hi Sonxay,

I had this problem as well. You just need to close the script error dialog box and run the simulation again. Once you do this, the simulation will run as it is supposed to!

R

**Comment by dhondta** [comment]
Hi all,

@sonxay : I see in your screenshot that your version of the framework uses the Rhino Javascript engine. This could mean that you use a former Contiki instance that still uses OpenJDK 7.

Issue #20 was already handled about this problem, that's why I added `update` and `versions` commands to update Contiki and RPL-Attacks together fixing the problem of the Javascript engine with the following line in `templates/experiment/script.js`:

```
// since OpenJDK 8, Rhino JS Engine is replaced by Nashorn
// this line provides compatibility so that 'importPackage' can be used
try { load("nashorn:mozilla_compat.js"); } catch(e) {}
importPackage(java.io);
```

If you upgrade your OS, it would normally upgrade OpenJDK from 7 to 8, then change the Javascript engine from Rhino to Nashorn, and I think you should then not experience your problem again.

**Comment by sonxay** [comment]
Hi...Sorry
could you help me.

I can not active this file cause I wanna to improve your file to do more simulation like : Throughput , end to end delay ....if i can not active this file , it is mean i can not fix anything 

so could you help me pl

thanks
Sonya


![screen shot 2017-06-20 at 10 35 22 pm](https://user-images.githubusercontent.com/29446281/27342005-184e64d8-5609-11e7-8504-bb691f67074c.png)

**Comment by dhondta** [comment]
Please try the following :
1. As a first try, just remove the aforementioned lines from the Javascript (that is, lines 1 to 4) and try restarting the simulation.
2. If it does not work, please `apt-get update` and `upgrade` your OS, then in *RPL-Attacks*, launch the `update` command.

Then please tell me if you still have any problem.

**Comment by sonxay** [comment]
Hi...i just wanna say ..Thank you so much for your helping 

I wish you to be happy and successful for your life 

take care 

sonxay

**Comment by dhondta** [comment]
You're welcome, sonxay, that's a pleasure.
I wish you the same !

**Comment by jemmyjell55** [comment]
@sonxay could u help me in to understand the script
