### ISSUE TITLE
Version Number Modification Attack Report has wrong DODAG Graph in it?

### ISSUE THREAD

**Issue by mueller91** [dhondta/rpl-attacks#33]
Dear all,
please look at the attached [report.pdf](https://github.com/dhondta/rpl-attacks/files/1707973/report.pdf), which i generated using `fab demo`. To me, it looks like the DODAG graph in the report is the one from the Blackhole Attack? You can see that after the attack, the malicious node is parent of a majority of the surrounding nodes.

**Comment by dhondta** [comment]
Hi @mueller91 !

Thank you very much for this feedback. Your interpretation makes sense, I mean that it should have provided something different for the DODAG.
Did you run the simulation multiple times to see if it gives the expected result ?

**Comment by mueller91** [comment]
Hi @dhondta 

thank you very much for your reply! I did run the test several times, the outcome looks similar in all cases. Please see, for example, [report2.pdf](https://github.com/dhondta/rpl-attacks/files/1710462/report.pdf), also created via `fab demo`, which has the same issue as the report above.
I'm just wondering if nobody else experienced this issue? How does it look like when you run `fab demo`?

**Comment by dhondta** [comment]
Hi @mueller91 

I just started a few simulations and that is kind of weird ; it's just like the *Version Number Modification Attack* had the effect of the *Blackhole Attack*...

This requires further investigation as the ContikiRPL implementation could have been patched and the related attack building blocks could be obsolete.

**Comment by mueller91** [comment]
Can you provide me with the version of Contiki that you have been using when it worked? I really find your project useful and would like to help out finding the issue.

**Comment by dhondta** [comment]
This is difficult to say ; at the time of the academical project, I did not implement a functionality to check for the versions (of Contiki and the framework itself). So, I did not noted the version when the related attack simulation was run when it gave me the expected result.
Maybe it could be interesting to search for commits in the Contiki repository from June 2016 in order to figure out if significant changes were made to the ContikiRPL implementation. For the time being, unfortunately I do not have time enough to go deeper for checking that.
Please let me know if you find some relevant information about that.

**Comment by mueller91** [comment]
I found that building blocks such as `"rpl_recalculate_ranks();", null` were ignored. After fixing this, i reran the experiments, seems to be better now; see the following files: [report_blackhole.pdf](https://github.com/dhondta/rpl-attacks/files/1741097/report.pdf) and [report_version_number.pdf](https://github.com/dhondta/rpl-attacks/files/1741098/report.pdf)

Check out my commit above. It's a quick hack, so feel free to re-implement it yourself. Also, the deletion of the vagrant file was a misclick.

**Comment by dhondta** [comment]
My gosh, I guess I could have used something less cute in the building-blocks' JSON in the version at the time when I made the academical report and that, afterwards, I made slight changes without figuring out I let something missing...

Anyway, thank you so much for finding this. Please submit it as a Pull Request so that I can get it fixed in the master project.
