### ISSUE TITLE
MOTES Lorawan

### ISSUE THREAD

**Issue by OniremE** [dhondta/rpl-attacks#51]
Hi, i need a suggest for simulate motes Lorawan and analyze the security features in this protocol

**Comment by dhondta** [comment]
Hi @OniremE 
There is a relatively recent project which aimed to port Contiki for LoRa platform, [KRATOS](https://github.com/rajeev1986/contikios-for-lora), you can see its presentation [here](https://contikios4lora.github.io/contikios-lora/).
But the problem is that you won't be able to simply replace the `contiki` folder used by RPL Attacks Framework with the one of [KRATOS](https://github.com/rajeev1986/contikios-for-lora) as it lacks some features from the original Contiki. However, it should be possible to port some features (namely [Contiki's `tools`](https://github.com/contiki-os/contiki/tree/master/tools) and especially Cooja) to KRATOS so that it becomes possible to put RPL Attacks Framework above.
