### ISSUE TITLE
Implementation VeRa - Version Number and Rank Authentication

### ISSUE THREAD

**Issue by trannhoduc** [dhondta/rpl-attacks#73]
Hi everyone,

I am going to implement VeRA - Version Number and Rank Authentication to detect and prevent RPL network from Decrease Rank Attack and Increase Verion Number Attack.
I have studied[ this paper](https://www.researchgate.net/publication/220747423_VeRA_-_Version_number_and_rank_authentication_in_RPL) about VeRa, and know that there are step to use this method

1. Upon initialization, a DODAG root generates a random number r and calculates a hash chain for each Version and Rank, then compute MAC_V1(Rmrh). Finally, the DODAG root multicasts a DIO message with V0, MACV1(Rmrh), the initial value InitVN of the Version Number, and the signature. The DODAG
root can resend the signed DIO message until the first Version
Number update occurs
2. Upon receiving the signed DIO message, each intermediate node verifies the authentication data and in case of success
saves the signature, the root V0 of the Version Number hash chain, the MAC value, and the initial value InitV N of the Version Number. When the trickle timer expires, it multicasts to all neighbors the DIO message (M#2) according to 
3. Upon Version Number update, the DODAG root sends a DIO message (M#3) with the following parameters: next
Version Number value V N as described in [11], next Version Number hash chain element Vi, MACVi+1(Rmrh) a message
authentication code (MAC) value over the Max Rank hash value Rmrh = Ri+1;l with the next Version Number hash chain element Vi+1 as the key, and a Rank element value Rsender = hRankroot(xi), where Rankroot is the new Rank value2 of the DODAG root.
4. Upon receiving a DIO message with a new Version Number or new Rank value, an intermediate node can easily verify the message because, if the Version Number is increased by the DODAG root, hi(Vi) must be equal to V0. 

So, now I am finding more materials about VeRa to help me implement this project. 

Furthermore, I can relatively understand and implement this method, but I don't know where exactly I can modidy the code ?
For example, I know all the function is in the folder contiki/core/net/rpl, but what files and function I need to modify, where is DIO content locate ...

Can you show it to me! 
Thank you very much.

**Comment by dhondta** [comment]
Hi @trannhoduc 
This is indeed the hard part. I had to figure this out before implementing my demonstration attacks.
The work method you shall follow is explained [here](https://rpl-attacks.readthedocs.io/en/latest/building-blocks/#creation-process) and applies to creating new attack building blocks. In this case, you will deal with constants tuning or simple replacements in the code.

**Constants tuning & Simple replacements in the RPL library**
This [part of the documentation](https://rpl-attacks.readthedocs.io/en/latest/building-blocks) shows how to apply simple replacements in code. If it is not enough, you can also use an external version of `core/net/rpl`. You will see examples [here](https://rpl-attacks.readthedocs.io/en/latest/building-blocks/#real-examples).

-----
If you need to tune ContikiRPL further, you shall use a different work method ;
1. Copy the `core/net/rpl` library of Contiki to a new folder where you will apply your modifications
2. In the framework, while `make`-ing your simulation, enter `ext_lib=path/to/your/core/net/rpl` at the end to set this particular parameter
3. Run your simulation and see if the results are what you expect
4. If not, go back to 2.

**External RPL library**
Unfortunately, this feature is poorly documented. It relates to the `ext_lib` of the `make` command, this is documented [here](https://rpl-attacks.readthedocs.io/en/latest/commands). Due to the way campaign JSON file is parsed, you can simply define the path to your external library with the `ext_lib` key under your simulation definition.
The method is then (1) to copy-paste the native core RPL library from Contiki, (2) to tune it accordingly and (3) to reference it in your campaign JSON file.
